Repository prgrms-be-devcourse/NBE2-3-1-team7, pull requests merged in 2024-12, with the labels that each got.

#11 [docs] PR, Isuue 템플릿 설정
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/ISSUE_TEMPLATE/refactor-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Docs

#16 [feat] 장바구니에 담긴 물품 조회
  src/main/java/com/example/shop/domain/cart/CartDetailRepository.java
  src/main/java/com/example/shop/domain/product/Product.java
  src/main/java/com/example/shop/user/controller/CartController.java
  src/main/java/com/example/shop/user/dto/CartDetailResponse.java
  src/main/java/com/example/shop/user/service/CartService.java
Labels: Feature

#21 [feature] 이메일 인증 코드 메일 전송
  src/main/java/com/example/shop/auth/controller/AuthController.java
  src/main/java/com/example/shop/auth/dto/EmailCodeRequest.java
  src/main/java/com/example/shop/auth/repository/EmailCodeRepository.java
  src/main/java/com/example/shop/auth/repository/RefreshTokenRepository.java
  src/main/java/com/example/shop/auth/service/AuthService.java
  src/main/java/com/example/shop/auth/service/EmailCodeUtil.java
  src/main/java/com/example/shop/global/EmailSender.java
  src/main/java/com/example/shop/global/config/AsyncConfig.java
  src/main/java/com/example/shop/global/config/SecurityConfig.java
  src/main/java/com/example/shop/global/config/auth/JwtAuthenticationFilter.java
  src/main/java/com/example/shop/global/config/db/RedisConfig.java
  src/main/java/com/example/shop/global/exception/EmailCreationException.java
  src/main/java/com/example/shop/global/exception/EmailSendException.java
  src/main/java/com/example/shop/global/exception/ErrorCodes.java
  src/main/java/com/example/shop/global/response/GlobalExceptionHandler.java
Labels: Feature

#27 [feat] 회원가입 검증추가 및 에러 해결
  src/main/java/com/example/shop/auth/dto/SignUpResponse.java
  src/main/java/com/example/shop/auth/service/AuthService.java
  src/main/java/com/example/shop/domain/BaseEntity.java
  src/main/java/com/example/shop/domain/user/UserRepository.java
  src/main/java/com/example/shop/global/config/auth/CustomAuthenticationProvider.java
  src/main/java/com/example/shop/global/config/auth/CustomUserDetailsService.java
  src/main/java/com/example/shop/global/config/auth/JwtAuthenticationFilter.java
  src/main/java/com/example/shop/global/config/auth/JwtProvider.java
  src/main/java/com/example/shop/global/exception/DuplicatedEmailException.java
  src/main/java/com/example/shop/global/exception/ErrorCodes.java
  src/main/java/com/example/shop/global/exception/LogInNotMatch.java
  src/main/java/com/example/shop/global/exception/LogInNotMatchException.java
  src/main/java/com/example/shop/global/exception/NoAuthAccessTokenException.java
  src/main/java/com/example/shop/global/exception/NoAuthorizationHeaderException.java
  src/main/java/com/example/shop/global/exception/NoBearerException.java
  src/main/java/com/example/shop/global/exception/UserNotFoundException.java
  src/main/java/com/example/shop/user/service/CartService.java
Labels: Feature

#34 Feature/#29 장바구니에 담긴 물품 삭제
  src/main/java/com/example/shop/domain/cart/CartDetailRepository.java
  src/main/java/com/example/shop/global/exception/CartProductNotFoundException.java
  src/main/java/com/example/shop/global/exception/ErrorCodes.java
  src/main/java/com/example/shop/global/exception/NoAuthenticationException.java
  src/main/java/com/example/shop/global/response/GlobalExceptionHandler.java
  src/main/java/com/example/shop/global/util/SecurityUtil.java
  src/main/java/com/example/shop/user/controller/CartController.java
  src/main/java/com/example/shop/user/service/CartService.java
Labels: Feature, Bug, Refactor

#33 feat: 메뉴 조회 기능 추가
  build.gradle
  src/main/java/com/example/shop/user/controller/ProductController.java
  src/main/java/com/example/shop/user/dao/UserDao.java
  src/main/java/com/example/shop/user/dto/ProductResponse.java
  src/main/java/com/example/shop/user/mapper/UserMapper.java
  src/main/java/com/example/shop/user/service/ProductService.java
  src/main/resources/application.yml
  src/main/resources/mappers/usermapper.xml
Labels: Feature

#37 [feature] 물품 조회
  build.gradle
  src/main/java/com/example/shop/admin/controller/AdminProductController.java
  src/main/java/com/example/shop/admin/dao/AdminDAO.java
  src/main/java/com/example/shop/admin/dto/ProductTO.java
  src/main/java/com/example/shop/admin/mapper/AdminMapper.java
  src/main/java/com/example/shop/admin/service/AdminProductService.java
  src/main/resources/application.yml
  src/main/resources/mappers/adminMapper.xml
Labels: Feature

#41 [feat] 장바구니에 담긴 물품 전체 삭제
  src/main/java/com/example/shop/domain/cart/CartDetailRepository.java
  src/main/java/com/example/shop/global/exception/CartEmptyException.java
  src/main/java/com/example/shop/global/exception/ErrorCodes.java
  src/main/java/com/example/shop/user/controller/CartController.java
  src/main/java/com/example/shop/user/service/CartService.java
Labels: Feature, Refactor

#38 [feat] 장바구니에 담긴 특정 물품 수량 변경 기능 추가
  src/main/java/com/example/shop/user/controller/CartController.java
  src/main/java/com/example/shop/user/dto/UpdateCartQuantityRequest.java
  src/main/java/com/example/shop/user/service/CartService.java
Labels: Feature

#43 [feature] 물품수정
  src/main/java/com/example/shop/admin/controller/AdminProductController.java
  src/main/java/com/example/shop/admin/dao/AdminDAO.java
  src/main/java/com/example/shop/admin/dto/ProductUpdateRequest.java
  src/main/java/com/example/shop/admin/mapper/AdminMapper.java
  src/main/java/com/example/shop/admin/service/AdminProductService.java
  src/main/resources/application.yml
  src/main/resources/mappers/adminMapper.xml
Labels: Feature

#46 [feat] 주문 생성
  src/main/java/com/example/shop/domain/cart/CartDetailRepository.java
  src/main/java/com/example/shop/domain/order/DeliveryInfo.java
  src/main/java/com/example/shop/domain/order/Order.java
  src/main/java/com/example/shop/domain/order/OrderDetail.java
  src/main/java/com/example/shop/domain/order/OrderRepository.java
  src/main/java/com/example/shop/domain/product/Product.java
  src/main/java/com/example/shop/domain/product/ProductRepository.java
  src/main/java/com/example/shop/domain/user/User.java
  src/main/java/com/example/shop/global/exception/CartEmptyException.java
  src/main/java/com/example/shop/global/exception/EmptyCartException.java
  src/main/java/com/example/shop/global/exception/EmptyOrderDetailException.java
  src/main/java/com/example/shop/global/exception/ErrorCodes.java
  src/main/java/com/example/shop/global/exception/NotEnoughQuantityException.java
  src/main/java/com/example/shop/user/controller/CartController.java
  src/main/java/com/example/shop/user/controller/OrderController.java
  src/main/java/com/example/shop/user/dto/CreateOrderRequest.java
  src/main/java/com/example/shop/user/dto/CreateOrderResponse.java
  src/main/java/com/example/shop/user/service/CartService.java
  src/main/java/com/example/shop/user/service/OrderService.java
Labels: Feature, Bug, Refactor

#48 [feature] 로그인 리프레시 토큰 재발급
  src/main/java/com/example/shop/auth/controller/AuthController.java
  src/main/java/com/example/shop/auth/dto/AccessTokenResponse.java
  src/main/java/com/example/shop/auth/dto/SignInResponse.java
  src/main/java/com/example/shop/auth/repository/RefreshTokenRepository.java
  src/main/java/com/example/shop/auth/service/AuthService.java
  src/main/java/com/example/shop/domain/user/RefreshToken.java
  src/main/java/com/example/shop/global/config/auth/JwtProvider.java
  src/main/java/com/example/shop/global/exception/ErrorCodes.java
  src/main/java/com/example/shop/global/exception/RefreshTokenExpiredException.java
Labels: Feature, Refactor

#56 [feature] 주문 배송 알림 메일 발송
  build.gradle
  src/main/java/com/example/shop/admin/dao/OrderDeliveryRepository.java
  src/main/java/com/example/shop/admin/dto/OrderDeliveryRequest.java
  src/main/java/com/example/shop/admin/mapper/AdminMapper.java
  src/main/java/com/example/shop/admin/service/OrderAdminService.java
  src/main/java/com/example/shop/admin/service/OrderDeliveryUtil.java
  src/main/java/com/example/shop/auth/service/AuthService.java
  src/main/java/com/example/shop/batch/DeliveryOrderReader.java
  src/main/java/com/example/shop/batch/OrderUpdateSenderWriter.java
  src/main/java/com/example/shop/batch/config/EmailNotificationJobConfig.java
  src/main/java/com/example/shop/batch/config/EmailScheduler.java
  src/main/java/com/example/shop/batch/util/OrderDeliveryBatchUtil.java
  src/main/java/com/example/shop/domain/cart/CartDetailRepository.java
  src/main/java/com/example/shop/domain/order/OrderRepository.java
  src/main/java/com/example/shop/domain/product/ProductRepository.java
  src/main/java/com/example/shop/domain/user/UserRepository.java
  src/main/java/com/example/shop/global/config/AsyncConfig.java
  src/main/java/com/example/shop/global/config/db/RedisConfig.java
  src/main/java/com/example/shop/global/util/EmailSender.java
  src/main/java/com/example/shop/user/service/OrderService.java
  src/main/resources/application.yml
  src/main/resources/mappers/adminMapper.xml
  src/test/java/com/example/shop/admin/dao/OrderDeliveryRepositoryTest.java
  src/test/java/com/example/shop/admin/service/OrderDeliveryUtilTest.java
  src/test/java/com/example/shop/batch/OrderUpdateSenderWriterTest.java
Labels: Feature, Bug, Test

#53 [feat] 주문 수정
  src/main/java/com/example/shop/domain/BaseEntity.java
  src/main/java/com/example/shop/domain/order/Order.java
  src/main/java/com/example/shop/domain/order/OrderDetail.java
  src/main/java/com/example/shop/domain/order/OrderRepository.java
  src/main/java/com/example/shop/domain/product/Product.java
  src/main/java/com/example/shop/global/exception/ErrorCodes.java
  src/main/java/com/example/shop/global/exception/NotModifiableOrderException.java
  src/main/java/com/example/shop/global/exception/OrderDetailNotFoundException.java
  src/main/java/com/example/shop/global/exception/OrderNotFoundException.java
  src/main/java/com/example/shop/global/exception/UnauthorizedOrderAccessException.java
  src/main/java/com/example/shop/user/controller/OrderController.java
  src/main/java/com/example/shop/user/dto/CreateOrderRequest.java
  src/main/java/com/example/shop/user/dto/OrderResponse.java
  src/main/java/com/example/shop/user/dto/UpdateOrderRequest.java
  src/main/java/com/example/shop/user/service/OrderService.java
Labels: Feature, Bug, Refactor

#58 [feat] 메뉴 검색 기능 추가
  .gitignore
  build.gradle
  src/main/java/com/example/shop/ShopApplication.java
  src/main/java/com/example/shop/global/config/db/RedisConfig.java
  src/main/java/com/example/shop/user/controller/ProductController.java
  src/main/java/com/example/shop/user/dao/UserDao.java
  src/main/java/com/example/shop/user/dto/ProductResponse.java
  src/main/java/com/example/shop/user/mapper/UserMapper.java
  src/main/java/com/example/shop/user/service/ProductService.java
  src/main/resources/mappers/usermapper.xml
Labels: Feature, Refactor

#61 [feat] 특정 주문에 대한 조회
  src/main/java/com/example/shop/domain/order/OrderRepository.java
  src/main/java/com/example/shop/global/exception/ErrorCodes.java
  src/main/java/com/example/shop/user/controller/CartController.java
  src/main/java/com/example/shop/user/controller/OrderController.java
  src/main/java/com/example/shop/user/service/OrderService.java
Labels: Feature

#64 [feat] 주문 정보 수정 시 캐싱된 주문 수정
  src/main/java/com/example/shop/admin/dao/OrderDeliveryRepository.java
  src/main/java/com/example/shop/admin/service/OrderAdminService.java
  src/main/java/com/example/shop/batch/DeliveryOrderReader.java
  src/main/java/com/example/shop/batch/OrderUpdateSenderWriter.java
  src/main/java/com/example/shop/batch/util/OrderDeliveryBatchUtil.java
  src/main/java/com/example/shop/user/service/OrderService.java
  src/test/java/com/example/shop/admin/dao/OrderDeliveryRepositoryTest.java
  src/test/java/com/example/shop/batch/OrderUpdateSenderWriterTest.java
Labels: Feature, Style, Test

#57 [feat] 물품상세조회
  src/main/java/com/example/shop/admin/controller/AdminProductController.java
  src/main/java/com/example/shop/admin/dao/AdminDAO.java
  src/main/java/com/example/shop/admin/dto/ProductCreateRequest.java
  src/main/java/com/example/shop/admin/dto/ProductFilterRequest.java
  src/main/java/com/example/shop/admin/mapper/AdminMapper.java
  src/main/java/com/example/shop/admin/service/AdminProductService.java
  src/main/resources/mappers/adminMapper.xml
Labels: Feature

#66 [feat] 주문 목록 조회
  src/main/java/com/example/shop/common/dto/PageResponse.java
  src/main/java/com/example/shop/domain/order/OrderRepository.java
  src/main/java/com/example/shop/user/controller/OrderController.java
  src/main/java/com/example/shop/user/dto/OrderListResponse.java
  src/main/java/com/example/shop/user/service/OrderService.java
Labels: Feature

#69 [refactor] 예외 클래스 추가 및 예외 처리 로직 수정
  src/main/java/com/example/shop/global/exception/ErrorCodes.java
  src/main/java/com/example/shop/global/exception/ProductIdNotFoundException.java
  src/main/java/com/example/shop/global/exception/ProductSearchEmptyException.java
  src/main/java/com/example/shop/global/exception/ProductsEmptyException.java
  src/main/java/com/example/shop/user/controller/ProductController.java
  src/main/java/com/example/shop/user/service/ProductService.java
Labels: Refactor

#71 [feat] 관리자 주문 배송 일괄 처리
  src/main/java/com/example/shop/admin/controller/AdminOrderController.java
  src/main/java/com/example/shop/admin/dto/OrderDeliveryListRequest.java
  src/main/java/com/example/shop/admin/dto/OrderDeliveryRequest.java
  src/main/java/com/example/shop/admin/service/AdminOrderService.java
  src/main/java/com/example/shop/batch/OrderUpdateSenderWriter.java
  src/main/java/com/example/shop/user/service/OrderService.java
  src/test/java/com/example/shop/batch/OrderUpdateSenderWriterTest.java
Labels: Feature, Style

#72 [feat] 관리자 주문 조회 기능
  .gitignore
  build.gradle
  src/main/java/com/example/shop/admin/controller/AdminOrderController.java
  src/main/java/com/example/shop/admin/dto/AdminOrderListResponse.java
  src/main/java/com/example/shop/admin/dto/AdminOrderResponse.java
  src/main/java/com/example/shop/admin/dto/OrderSearchRequest.java
  src/main/java/com/example/shop/admin/service/AdminOrderService.java
  src/main/java/com/example/shop/common/dto/OrderListResponse.java
  src/main/java/com/example/shop/common/dto/OrderResponse.java
  src/main/java/com/example/shop/domain/order/OrderRepository.java
  src/main/java/com/example/shop/domain/order/OrderRepositoryCustom.java
  src/main/java/com/example/shop/domain/order/OrderRepositoryImpl.java
  src/main/java/com/example/shop/domain/user/User.java
  src/main/java/com/example/shop/global/config/QuerydslConfig.java
  src/main/java/com/example/shop/user/controller/OrderController.java
  src/main/java/com/example/shop/user/service/OrderService.java
Labels: Feature, Refactor

#77 feat: 주문 취소 기능 추가
  src/main/java/com/example/shop/domain/order/OrderRepository.java
  src/main/java/com/example/shop/user/controller/OrderController.java
  src/main/java/com/example/shop/user/service/OrderService.java
Labels: Feature

#78 [refactor] html 하드 코딩 리팩터링
  build.gradle
  src/main/java/com/example/shop/admin/service/OrderDeliveryUtil.java
  src/main/java/com/example/shop/auth/service/EmailCodeUtil.java
  src/main/java/com/example/shop/global/util/TemplateEnginUtil.java
  src/main/resources/templates/auth-code-email.html
  src/main/resources/templates/delivery-email.html
  src/test/java/com/example/shop/admin/service/OrderDeliveryUtilTest.java
  src/test/java/com/example/shop/auth/service/EmailCodeUtilTest.java
Labels: Refactor

#81 [feature] 주문 취소 시 캐싱된 데이터 삭제
  src/main/java/com/example/shop/admin/service/AdminOrderService.java
  src/main/java/com/example/shop/user/service/OrderService.java
Labels: Feature, Bug

#85 [refactor] 캐싱하는 값을 orderid가 아닌 ordernumber로 수정
  build.gradle
  src/main/java/com/example/shop/admin/dto/OrderDeliveryRequest.java
  src/main/java/com/example/shop/admin/service/AdminOrderService.java
  src/main/java/com/example/shop/admin/service/OrderDeliveryUtil.java
  src/main/java/com/example/shop/user/service/OrderService.java
  src/main/resources/mappers/adminMapper.xml
  src/main/resources/templates/delivery-email.html
  src/test/java/com/example/shop/admin/dao/OrderDeliveryRepositoryTest.java
  src/test/java/com/example/shop/admin/service/OrderDeliveryUtilTest.java
  src/test/java/com/example/shop/batch/OrderUpdateSenderWriterTest.java
Labels: Bug, Refactor

#67 [refactor] 기능 리팩토링
  src/main/java/com/example/shop/admin/controller/AdminProductController.java
  src/main/java/com/example/shop/admin/mapper/AdminMapper.java
  src/main/java/com/example/shop/admin/service/AdminProductService.java
  src/main/java/com/example/shop/global/exception/DataInsertFailedException.java
  src/main/java/com/example/shop/global/exception/ErrorCodes.java
  src/main/java/com/example/shop/global/exception/ProductFilterNotFoundException.java
  src/main/java/com/example/shop/global/exception/ProductIDModifiedNotFoundException.java
  src/main/java/com/example/shop/global/exception/ProductNameNotInsertException.java
  src/main/java/com/example/shop/global/exception/ProductPriceNotInsertException.java
  src/main/java/com/example/shop/global/exception/ProductQuantityNotInsertException.java
  src/main/java/com/example/shop/global/exception/ProductUpdateFailedException.java
  src/main/resources/mappers/adminMapper.xml
Labels: Refactor

#88 [feat]로그아웃 및 회원탈퇴
  src/main/java/com/example/shop/auth/controller/AuthController.java
  src/main/java/com/example/shop/auth/dto/SignUpRequest.java
  src/main/java/com/example/shop/auth/repository/BlackListRepository.java
  src/main/java/com/example/shop/auth/repository/RefreshTokenRepository.java
  src/main/java/com/example/shop/auth/service/AuthService.java
  src/main/java/com/example/shop/domain/order/OrderRepository.java
  src/main/java/com/example/shop/domain/user/User.java
  src/main/java/com/example/shop/domain/user/UserStatus.java
  src/main/java/com/example/shop/global/config/SecurityConfig.java
  src/main/java/com/example/shop/global/config/auth/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/shop/global/config/auth/JwtAuthenticationFilter.java
  src/main/java/com/example/shop/global/config/auth/JwtProvider.java
  src/main/java/com/example/shop/global/exception/ErrorCodes.java
  src/main/java/com/example/shop/global/exception/LogOutTokenException.java
  src/main/java/com/example/shop/global/exception/UndeliveredOrderExistsException.java
Labels: Feature

#89 [docs] 장바구니 주문 swagger 어노테이션 추가
  src/main/java/com/example/shop/admin/controller/AdminOrderController.java
  src/main/java/com/example/shop/admin/dto/OrderSearchRequest.java
  src/main/java/com/example/shop/domain/order/OrderRepository.java
  src/main/java/com/example/shop/domain/order/OrderRepositoryImpl.java
  src/main/java/com/example/shop/user/controller/CartController.java
  src/main/java/com/example/shop/user/controller/OrderController.java
  src/main/java/com/example/shop/user/dto/CartResponse.java
Labels: Docs, Refactor

#91 fix: 토큰 재발급 request 수정
  src/main/java/com/example/shop/auth/controller/AuthController.java
  src/main/java/com/example/shop/auth/dto/ReIssueTokenRequest.java
  src/main/java/com/example/shop/auth/service/AuthService.java
Labels: Bug

#92 [Test] TestContainers와 H2로 DB 테스트하기
  .github/workflows/pr-ci.yaml
  build.gradle
  src/main/java/com/example/shop/ShopApplication.java
  src/main/java/com/example/shop/auth/controller/AuthController.java
  src/main/java/com/example/shop/global/config/db/JpaConfig.java
  src/main/java/com/example/shop/global/config/db/RedisConfig.java
  src/test/java/com/example/shop/ShopApplicationTests.java
  src/test/java/com/example/shop/admin/dao/OrderDeliveryRepositoryTest.java
  src/test/java/com/example/shop/batch/OrderUpdateSenderWriterTest.java
  src/test/java/com/example/shop/global/config/RedisTestConfig.java
  src/test/java/com/example/shop/global/config/RedisTestContainer.java
  src/test/java/com/example/shop/global/setting/ControllerTest.java
  src/test/java/com/example/shop/global/setting/RedisTest.java
  src/test/java/com/example/shop/global/setting/RepositoryTest.java
  src/test/java/com/example/shop/global/setting/ServiceTest.java
  src/test/java/com/example/shop/global/util/EmailSenderTest.java
  src/test/resources/application-test.yaml
  src/test/resources/sql/order-data.sql
Labels: Feature, Test

#94 [Refactor] 컨트롤러 응답 수정
  src/main/java/com/example/shop/admin/controller/AdminProductController.java
Labels: Refactor

#97 [Test] 배치 작업 테스트
  src/main/java/com/example/shop/domain/order/OrderRepository.java
  src/main/resources/application.yml
  src/test/java/com/example/shop/batch/config/EmailNotificationJobConfigTest.java
  src/test/java/com/example/shop/global/setting/BatchTest.java
  src/test/resources/application-test.yaml
  src/test/resources/sql/order-dump.sql
Labels: Refactor, Test

#98 [docs] 프로젝트 소개
  README.md
Labels: Docs

#99 [fix] 프로젝트 소개 이미지 수정
  README.md
Labels: Docs, Style
